# Generated by Django 4.1.5 on 2023-06-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_todouser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
