# Generated by Django 4.1.5 on 2023-06-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_alter_todo_item_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemodel',
            name='active',
        ),
    ]
